wsgi/myproject/accounts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^all-users/$', views.all_users, name='all-users'),
    url(r'^adduser/$', views.add_user, name='add_user'),
    url(r'^edit_user/(?P<user_id>\d+)/$', views.edit_user, name='edit_user'),
    url(r'^delete_user/(?P<user_id>\d+)/$', views.delete_user, name='delete_user'),
    url(r'^get_user_by_id/(?P<user_id>\d+)/$', views.get_user_by_id, name='get_user_by_id'),
    url(r'^get_user_query/(?P<query>\w+)/$', views.get_user_query, name='get_user_query'),
]

wsgi/myproject/myproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('products.urls', namespace="products")),
    url(r'^summernote/', include('django_summernote.urls')),
]

wsgi/myproject/products/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',views.index,name="index"),
    url(r'^create/{0,1}$',views.create_product,name="create_product"),
    url(r'^view/(\d+)$',views.view_product,name="view_product"),
    url(r'^edit/(\d*)$',views.edit_product,name="edit_product"),
    url(r'^delete/(\d+)$',views.delete_product,name="delete_product"),
    url(r'^brands/{0,1}$',views.list_brands,name="list_brands"),
    url(r'^brands/view/(\d+)$',views.view_brand,name="view_brand"),
    url(r'^brands/create$',views.create_brand,name="create_brand"),
    url(r'^brands/edit/(\d*)$',views.edit_brand,name="edit_brand"),
    url(r'^tags/{0,1}$',views.list_tags,name="list_tags"),
    url(r'^tags/create$',views.create_tag,name="create_tag"),
    url(r'^tags/view/(\d+)$',views.view_tag,name="view_tag"),
    url(r'^tags/edit/(\d*)$',views.edit_tag,name="edit_tag"),
]

wsgi/templates/base.html
{% load i18n admin_static %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
<title>{% block title %}{% endblock %}</title>
<link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.min.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/bootstrap-datetimepicker.min.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/metisMenu.min.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/timeline.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/morris.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/sb-admin-2.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/font-awesome.min.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/fileinput.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/typeaheadjs.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/chosen.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/app.css" %}" />
{% block extrastyle %}{% endblock %}
<!--[if lte IE 7]><link rel="stylesheet" type="text/css" href="{% block stylesheet_ie %}{% static "admin/css/ie.css" %}{% endblock %}" /><![endif]-->

{% block extrahead %}{% endblock %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
</head>
{% load i18n %}
<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}">

<!-- Container -->
<div class="wrapper">
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                {% block branding %}{% endblock %}
            </div>

            
            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="{% url "accounts:logout" %}"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <div class="navbar-default sidebar" role="navigation" id="sidebar">
                <div class="sidebar-nav navbar-collapse">
                    <ul id="side-menu" class="nav">
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input id="search" class="form-control" type="text" placeholder="Buscar..."/>
                                <span class="input-group-btn">
                                    <button class="btn btn-default">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                        </li>
                        {% if user.function == 'admin'%}
                        <li>
                            <a href="{% url "accounts:index" %}"><i class="fa fa-user fa-fw"></i> Usuarios</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <div id="page-wrapper" class="row">
                    {% block messages %}
                        {% if messages %}
                        <ul class="messagelist">
                            {% for message in messages %}
                              <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|capfirst }}</li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                    {% endblock messages %}
                    <!-- Content -->
                    {% block content %}

                    {% endblock %}
                    <!-- END Content -->
                    {% block footer %}<div id="footer"></div>{% endblock %}

        </div>
</div>
<!-- END Container -->
    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "js/moment.min.js" %}"></script>
    <script src="{% static "js/underscore-min.js" %}"></script>
    <script src="{% static "js/backbone-min.js" %}"></script>
    <script src="{% static "js/backbone.localStorage.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/raphael-min.js" %}"></script>
    <script src="{% static "js/morris.min.js" %}"></script>
    <script src="{% static "js/metisMenu.min.js" %}"></script>
    <script src="{% static "js/sb-admin-2.js" %}"></script>
    <script src="{% static "js/fileinput.js" %}"></script>
    <script src="{% static "js/typeahead.bundle.js" %}"></script>
    <script src="{% static "js/bootstrap-datetimepicker.min.js" %}"></script>
    <script src="{% static "js/chosen.jquery.js" %}"></script>
    <script src="{% static "js/app.js" %}"></script>
    <script src="{% static "js/fileinput/fileinput.js" %}"></script>
    <script src="{% static "js/fileinput/fileinput_locale_es.js" %}"></script>
    {% block extra_scripts %} {% endblock %}
</body>
</html>

wsgi/templates/base_light.html
{% load i18n admin_static %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
<title>{% block title %}{% endblock %}</title>
<link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.min.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/bootstrap-datetimepicker.min.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/metisMenu.min.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/timeline.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/morris.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/sb-admin-2.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/font-awesome.min.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/fileinput.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/typeaheadjs.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/chosen.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/app.css" %}" />
{% block extrastyle %}{% endblock %}
<!--[if lte IE 7]><link rel="stylesheet" type="text/css" href="{% block stylesheet_ie %}{% static "admin/css/ie.css" %}{% endblock %}" /><![endif]-->

<script src="{% static "js/jquery.min.js" %}"></script>
<script src="{% static "js/bootstrap.min.js" %}"></script>

{% block extrahead %}{% endblock %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
</head>
{% load i18n %}
<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}">

<!-- Container -->
<div class="wrapper">
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                {% block branding %}{% endblock %}
            </div>

            
            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="{% url "accounts:logout" %}"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <div class="navbar-default sidebar" role="navigation" id="sidebar">
                <div class="sidebar-nav navbar-collapse">
                    <ul id="side-menu" class="nav">
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input id="search" class="form-control" type="text" placeholder="Buscar..."/>
                                <span class="input-group-btn">
                                    <button class="btn btn-default">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                        </li>
                        {% if user.function == 'admin'%}
                        <li>
                            <a href="{% url "accounts:index" %}"><i class="fa fa-user fa-fw"></i> Usuarios</a>
                        </li>
                        {% endif %}
                        {% block sidebar-links %}
                        {% endblock %}
                    </ul>
                </div>
            </div>
        </nav>
        <div id="page-wrapper" class="row">
                    {% block messages %}
                        {% if messages %}
                        <ul class="messagelist">
                            {% for message in messages %}
                              <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|capfirst }}</li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                    {% endblock messages %}
                    <!-- Content -->
                    {% block content %}

                    {% endblock %}
                    <!-- END Content -->
                    {% block footer %}<div id="footer"></div>{% endblock %}

        </div>
</div>
<!-- END Container -->
    <script src="{% static "js/fileinput/fileinput.js" %}"></script>
    <script src="{% static "js/fileinput/fileinput_locale_es.js" %}"></script>
    <script src="{% static "js/chosen.jquery.js" %}"></script>
    {% block extra_scripts %} {% endblock %}
</body>
</html>

wsgi/templates/base_products.html
{% extends "base_site_light.html" %}

{% block sidebar-links %}

<li><a href="{% url 'products:index' %}">Productos</a></li>
<li><a href="{% url 'products:list_brands' %}">Marcas</a></li>
<li><a href="{% url 'products:list_tags' %}">Categorias</a></li>

{% endblock %}

wsgi/templates/base_site.html
{% extends "base.html" %}

{% block title %} Administración IntraG8 {% endblock %}

{% block branding %}
<a class="navbar-brand" href="{% url 'accounts:index' %}">Administración App-G8</a>
{% endblock %}

{% block nav-global %}{% endblock %}

wsgi/templates/base_site_light.html
{% extends "base_light.html" %}

{% block title %} Administración IntraG8 {% endblock %}

{% block branding %}
<a class="navbar-brand" href="{% url 'accounts:index' %}">Administración App-G8</a>
{% endblock %}

{% block nav-global %}{% endblock %}

wsgi/templates/categorias.html
{% extends "base_products.html" %}
{% load i18n admin_static %}

{% load product_filters %}

{% block extrastyle %} {% endblock %}

{% block coltype %} {% endblock %}

{% block bodyclass %}{{ block.super }} dashboard{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block messages %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert {% if message.tags %}{{ message.tags }}{% else %}alert-danger{% endif %} alert-dismissible" role="alert" style="margin-top:10px">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            {{message}}
            </div>
        {% endfor %}
    {%endif%}
{% endblock%}

{% block content %}
<div class="row">
    <h2 class="page-header">Categorias</h2>
</div>
<div class="row">
    <table class="table table-bordered table-hover table-striped">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Categoria Padre</th>
            </tr>
        </thead>
        <tbody>
            {% for x in categorias %}
            <tr>
                <td><a href="tags/view/{{x.id}}">{{x.nombre}}</a></td>
                <td>{{x.categoria_padre}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div class="row">
    <button class="btn btn-primary" data-toggle="modal" data-target="#agregar-categoria">Agregar Categoria</button>
</div>

<div class="modal fade" id="agregar-categoria" tabindex="-1" role="dialog" aria-labelledby="agregar-categoria" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="AgregarCategoriaLabel">Agregar Categoria</h4>
            </div>
            <form class="form-horizontal" action="{% url 'products:create_tag' %}" method="post">
                <div class="modal-body">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="nombre" class="col-sm-3 control-label">Nombre</label>
                        <div class="col-sm-8"><input type="text" id="nombre" name="nombre" class="form-control" oninvalid="InvalidMsg(this);"  oninput="InvalidMsg(this);" required></div>
                    </div>
                    <div class="form-group">
                        <label for="categoria_padre" class="col-sm-3 control-label">Categoria Padre</label>
                        <div class="col-sm-8">
                            <select class="form-control chosen-select" name="categoria_padre" id="categoria_padre">
                                <option value="">Seleccionar</option>
                                {% for x in categorias %}
                                <option value="{{x.id}}">{{x.nombre}}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                    <button type="submit" class="btn btn-primary">Guardar Categoria</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block extrahead %}

<script type="text/javascript">
function InvalidMsg(textbox) {
    if (textbox.value == '') {
        textbox.setCustomValidity('Campo Requerido');
    }
    else if (textbox.validity.typeMismatch){
        textbox.setCustomValidity('Valor Invalido');
    }
    else {
       textbox.setCustomValidity('');
    }
    return true;
}
</script>

{% endblock %}

{% block extra_scripts %}
<script type="text/javascript">
$(".chosen-select").chosen({max_selected_options: 1,width:"100%",no_results_text: "No se encontraron resultados"});
</script>
{% endblock %}

wsgi/templates/index.html
{% extends "base_site.html" %}
{% load i18n admin_static %}

{% block extrastyle %} {% endblock %}

{% block coltype %} {% endblock %}

{% block bodyclass %}{{ block.super }} dashboard{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block content %}
    <!-- Contend Here -->
{% endblock %}

{% block extra_scripts %}

{% endblock extra_scripts %}

{% block sidebar %}

{% endblock %}

wsgi/templates/login.html
{% load i18n staticfiles %}<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>IntraG8</title>

    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet" />
    <link href="{% static "css/metisMenu.min.css" %}" rel="stylesheet" />
    <link href="{% static "css/sb-admin-2.css" %}" rel="stylesheet">
    <link href="{% static "css/font-awesome.min.css" %}" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Por favor ingrese al sistema</h3>
                    </div>
                    <div class="panel-body">
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert {% if message.tags %}{{ message.tags }}{% else %}alert-danger{% endif %} alert-dismissible" role="alert" style="margin-top:10px">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                {{message}}
                                </div>
                            {% endfor %}
                        {% endif %}
                        <form action="{% url 'accounts:login' %}" method="POST">
                            {% csrf_token %} 
                            <fieldset>
                                <div class="form-group">
                                    <input class="form-control" type="text" placeholder="Email" name="login" autofocus>
                                </div>
                                <div class="form-group">
                                    <input class="form-control" type="password" placeholder="Contraseña" name="password" value="">
                                </div>
                                <input type="hidden" value="#" name='current'>
				<input type="hidden" value="{{ next }}" name="next">
                                <button class="btn btn-lg btn-success btn-block">Ingresar</button>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/metisMenu.min.js" %}"></script>
    <script src="{% static "js/sb-admin-2.js" %}"></script>
</body>
</html>

wsgi/templates/marcas.html
{% extends "base_products.html" %}
{% load i18n admin_static %}
{% load product_filters %}

{% block extrastyle %} {% endblock %}

{% block coltype %} {% endblock %}

{% block bodyclass %}{{ block.super }} dashboard{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block messages %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert {% if message.tags %}{{ message.tags }}{% else %}alert-danger{% endif %} alert-dismissible" role="alert" style="margin-top:10px">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            {{message}}
            </div>
        {% endfor %}
    {%endif%}
{% endblock%}

{% block content %}

<div class="row">
    <h2 class="page-header">Marcas</h2>
</div>
<div class="row">
    <table class="table table-bordered table-hover table-striped">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Imagen</th>
            </tr>
        </thead>
        <tbody>
            {% for x in marcas %}
            <tr>
                <td><a href="brands/view/{{x.id}}">{{x.nombre}}</a></td>
                <td><img src="{{x.imagen|get_thumb}}"></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div class="row">
	<button class="btn btn-primary" data-toggle="modal" data-target="#agregar-marca">Agregar Marca</button>
</div>

<div class="modal fade" id="agregar-marca" tabindex="-1" role="dialog" aria-labelledby="agregar-marca" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="AgregarMarcaLabel">Agregar Marca</h4>
            </div>
            <form enctype="multipart/form-data" class="form-horizontal" action="{% url 'products:create_brand' %}" method="post">
                <div class="modal-body">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="nombre" class="col-sm-3 control-label">Nombre</label>
                        <div class="col-sm-8"><input type="text" id="nombre" name="nombre" class="form-control" oninvalid="InvalidMsg(this);"  oninput="InvalidMsg(this);" required></div>
                    </div>
                    <div class="form-group">
                        <label for="foto" class="control-label col-sm-3">Subir Imagenes</label>
                        <div class="col-sm-8"><input name="foto" id="foto" type="file" class="file" data-show-upload="false" data-show-caption="false"></div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                    <button type="submit" class="btn btn-primary">Guardar Marca</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block extrahead %}

<script type="text/javascript">
function InvalidMsg(textbox) {
    if (textbox.value == '') {
        textbox.setCustomValidity('Campo Requerido');
    }
    else if (textbox.validity.typeMismatch){
        textbox.setCustomValidity('Valor Invalido');
    }
    else {
       textbox.setCustomValidity('');
    }
    return true;
}
</script>

{% endblock %}

wsgi/templates/view_brand.html
{% extends "base_products.html" %}
{% load i18n admin_static %}
{% load product_filters %}

{% block extrastyle %} {% endblock %}

{% block coltype %} {% endblock %}

{% block bodyclass %}{{ block.super }} dashboard{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block content %}
<div class="row">
    <h2 class="page-header">Editar {{marca.nombre}}</h2>
</div>
<form enctype="multipart/form-data" class="form-horizontal" action="../edit/{{marca.id}}" method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="nombre" class="col-sm-3 control-label">Nombre</label>
        <div class="col-sm-8"><input type="text" id="nombre" name="nombre" class="form-control" value="{{marca.nombre}}" oninvalid="InvalidMsg(this);"  oninput="InvalidMsg(this);" required></div>
    </div>
    {% if marca.imagen != '' %}
    <div class="row">
        <div class="row">
            <div class="col-sm-offset-4 col-sm-4"><img class="img-responsive" src="{{marca.imagen|get_thumb}}"></div>
        </div><br>
        <div class="row">
            <div class="col-sm-offset-5 col-sm-3">
                <label for="borrar">Borrar <input type="checkbox" name="borrar" id="borrar"></label>
            </div>
        </div>
    </div>
    {% else %}
    <input type="hidden" name="borrar" id="borrar" value="">
    {% endif %}
    <div class="form-group">
        <label for="foto" class="control-label col-sm-3">Subir Imagenes</label>
        <div class="col-sm-8"><input name="imagen" id="imagen" type="file" class="file" data-show-upload="false" data-show-caption="false"></div>
    </div>
    <div class="row">
        <div class="col-sm-offset-1 col-sm-10">
            <div class="pull-right" style="padding-bottom:15px">
                <a href=".."><span class="btn btn-danger">Regresar</span></a>
                <button class="btn btn-primary" type="submit">Guardar</button>
            </div>
        </div>
    </div>
</form>

{% endblock %}

{% block extrahead %}

<script type="text/javascript">
function InvalidMsg(textbox) {
    if (textbox.value == '') {
        textbox.setCustomValidity('Campo Requerido');
    }
    else if (textbox.validity.typeMismatch){
        textbox.setCustomValidity('Valor Invalido');
    }
    else {
       textbox.setCustomValidity('');
    }
    return true;
}
</script>

{% endblock %}

wsgi/templates/view_tag.html
{% extends "base_products.html" %}
{% load i18n admin_static %}
{% load product_filters %}

{% block extrastyle %} {% endblock %}

{% block coltype %} {% endblock %}

{% block bodyclass %}{{ block.super }} dashboard{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block content %}

<div class="row">
    <h2 class="page-header">Editar {{tag.nombre}}</h2>
</div>

<form method="post" action="../edit/{{tag.id}}" class="form-horizontal">
    {% csrf_token %}
    <div class="form-group">
        <label for="nombre" class="col-sm-3 control-label">Nombre</label>
        <div class="col-sm-8"><input type="text" name="nombre" id="nombre" value="{{tag.nombre}}" class="form-control" oninvalid="InvalidMsg(this);"  oninput="InvalidMsg(this);" required></div>
    </div>
    <div class="form-group">
        <label for="categoria_padre" class="col-sm-3 control-label">Categoria Padre</label>
        <div class="col-sm-8"><select class="form-control chosen-select" name="categoria_padre" id="categoria_padre">
            <option value="">Seleccionar</option>
            {% for x in categorias %}
            <option value="{{x.id}}"{% if tag.categoria_padre == x %}selected{% endif %}>{{x.nombre}}</option>
            {% endfor %}
        </select></div>
    </div>
    <div class="row">
        <div class="col-sm-offset-1 col-sm-10">
            <div class="pull-right" style="padding-bottom:15px">
                <a href=".."><span class="btn btn-danger">Regresar</span></a>
                <button class="btn btn-primary" type="submit">Guardar</button>
            </div>
        </div>
    </div>
</form>

{% endblock %}

{% block extrahead %}

<script type="text/javascript">
function InvalidMsg(textbox) {
    if (textbox.value == '') {
        textbox.setCustomValidity('Campo Requerido');
    }
    else if (textbox.validity.typeMismatch){
        textbox.setCustomValidity('Valor Invalido');
    }
    else {
       textbox.setCustomValidity('');
    }
    return true;
}
</script>

{% endblock %}

{% block extra_scripts %}
<script type="text/javascript">
$(".chosen-select").chosen({max_selected_options: 1,no_results_text: "No se encontraron resultados"});
</script>
{% endblock %}
        